<?php

namespace Components\JoloRecharge;

trait JoloAttributes
{
	private $api_base_url = 'https://joloapi.com';
	private $api_key;
	private $api_userid;			/* Jolo account user id */
	private $api_mode; 				/* test = 0, live = 1 */
	private $resp_type = 'json';	/* Response type json OR text */

	/**
	 * Read Doc if any doubts
	 * https://joloapi.com/docs.php
	 */

	/**
	 * Recharge API urls
	 * Leading / (slash) is must DO NOT DELETE IT
	 */
	private $mob_pre_rech_url	= '/api/recharge.php'; /* Mobile & Datacard */
	private $mob_post_rech_url	= '/api/cbill.php';    /* Mobile & Datacard */
	private $dth_rech_url		= '/api/recharge.php';
	private $land_broad_url		= '/api/cbill.php';	/* Landline & Broadband */

	/**
	 * Recharge status check URL for all types of recharge
	 * Mobile Prepaid Recharge, Mobile Postpaid Recharge, DTH Recharge, etc.
	 */
	private $recharge_check_url = '/api/rechargestatus_client.php';
	private $recharge_check_jolo_url = '/api/rechargestatus.php'; /* Jolo orderid */

	/**
	 * Report a dispute in recharge to this url using Jolo order Id (txn)
	 * You can report dispute transaction of last 10 days only.
	 */
	private $recharge_dispute_url = '/api/dispute_client.php';
	private $recharge_dispute_jolo_url = '/api/dispute.php'; /* Jolo orderid */

	/**
	 * Report a dispute in recharge to this url using your order Id (orderid)
	 * You can report dispute transaction of last 10 days only.
	 */
	private $dispute_report_client_url = '/api/dispute_client.php';


	/**
	 * Jolo API required params for creating agent, beneficiary
	 */
	private $required_params = [
		'mob_pre_recharge' => [
			'phone' 			=> true,  /* phone number to be recharged */
			'amount' 			=> true,  /* amount to be recharged */
			'orderid' 			=> true,
			'operator' 			=> true,  /* Operator code like JO for Jio */
		],
		'mob_post_recharge'=> [
			'phone' 			=> true,  /* phone number to be recharged */
			'amount' 			=> true,  /* amount to be recharged */
			'orderid' 			=> true,
			'operator' 			=> true,  /* Operator code like JO for Jio */
		],
		'dth_recharge'	   => [
			'dthid' 			=> true,  /* dth id of customer to be recharged */
			'amount' 			=> true,  /* amount to be recharged */
			'orderid' 			=> true,
			'operator' 			=> true,  /* Operator code like JO for Jio */
		],
	];

	/**
	 * Jolo API required params for transaction status check
	 */
	private $required_params_status = [
		'mob_pre_recharge' => [
			'txn' 			=> true,   /* Your order id (not jolo order id) */
		],
		'mob_post_recharge'=> [
			'txn' 			=> true,
		],
		'dth_recharge'	   => [
			'txn' 			=> true,
		],
	];

	/**
	 * Jolo API required params for transaction dispute
	 */
	private $required_params_dispute = [
		'mob_pre_recharge' => [
			'txn' 			=> true,   /* Your order id (not jolo order id) */
		],
		'mob_post_recharge'=> [
			'txn' 			=> true,
		],
		'dth_recharge'	   => [
			'txn' 			=> true,
		],
	];

	/**
	 * Jolo Mobile recharge API service types for transaction status check
	 */
	private $service_types = [
		'prepaid'		=> 1,	     /* Mobile prepaid recharge */
		'dth'			=> 2,	     /* DTH recharge */
		'postpaid'		=> 4,	     /* Mobile postpaid recharge */

		// Other services are not implemented yet
	];








	/**
	 * Jolo API required params for verifying agent, beneficiary
	 */
	private $required_params_verify = [
		'agent' => [
			'phone' 			=> true,
			'otp' 				=> true,
		],
		'beneficiary' => [
			'phone' 			=> true,
			'beneficiaryid' 	=> true,
			'otp' 				=> true,	/* otp send to beneficiary mobile number */
		],
		'transfer' => [
			'txn' 				=> true,
		],
	];

	/**
	 * Jolo API required params for getting detail of agent, beneficiary
	 */
	private $required_params_detail = [
		'agent' => [
			'phone' 			=> true,
		],
		'beneficiary' => [
			'beneficiaryid' 	=> true,
		],
		'balance' => [
			// nothing required, just api key
		],
	];

	/**
	 * Jolo API required params for deleting beneficiary
	 */
	private $required_params_delete = [
		'beneficiary' => [
			'beneficiaryid' 	=> true,
		],
	];

	/**
	 * Jolo API required params for checking balance and bank account
	 */
	private $required_params_check = [
		'balance' => [
			// No params is required for this API call but api_key and 
			// it will be provided by prepareParams() method
		],
		'bank' => [
			'phone' 			=> true,
			'beneficiary_account_no' => true,
			'beneficiary_ifsc'	=> true,
			'orderid'			=> true,	/* order id generated by website (me) */
		],
	];

	private $CUSTOM_ERROR_CODE  = 999;       /* custom error code. Read JoloError */

}