<?php

namespace Components\JoloBank;

trait JoloAttributes
{
	private $api_base_url = 'https://jolosoft.com';
	private $api_key;
	private $api_mode; 				/* test = 0, live = 1 */

	/**
	 * Read Doc if any doubts
	 * https://jolosoft.com/docs.php
	 */

	/**
	 * Agent signup / verify / detail
	 * Leading / (slash) is must DO NOT DELETE IT
	 */
	private $agent_signup_url = '/dmr/cdmr_signup.php';
	private $agent_verify_url = '/dmr/cdmr_signup_verify.php';
	private $agent_detail_url = '/dmr/cdmr_detail.php';
	
	/**
	 * Beneficiary signup / verify / detail / delete
	 * Leading / (slash) is must DO NOT DELETE IT
	 */
	private $beneficiary_registration_url = '/dmr/cdmr_beneficiary_reg.php';
	private $beneficiary_verify_url = '/dmr/cdmr_beneficiary_reg_verify.php';
	private $beneficiary_detail_url = '/dmr/cdmr_beneficiary_detail.php';
	private $beneficiary_delete_url = '/dmr/cdmr_beneficiary_del.php';
	
	/**
	 * Money transfer
	 * Leading / (slash) is must DO NOT DELETE IT
	 */ 
	private $transfer_money_url = '/dmr/cdmr_transfer.php';
	private $transfer_status_check_url = '/dmr/cdmr_transfer_status.php';

	private $balance_check_url = '/api/balance.php';

	/**
	 * Jolo charges Rs. 4.xx fee for every bank account check
	 * Leading / (slash) is must DO NOT DELETE IT
	 */
	private $bank_check_url = '/dmr/cdmr_account_check.php';

	/**
	 * Jolo API required params for creating agent, beneficiary
	 */
	private $required_params = [
		'agent' => [
			'name' 				=> true,
			'phone' 			=> true,
			'email' 			=> true,
			'address' 			=> true,
		],
		'beneficiary' => [
			'phone' 			=> true,
			'beneficiary_name'	=> true,
			'beneficiary_ifsc'	=> true,
			'beneficiary_account_no' => true,		/* Bank account number */
		],
		'transfer' => [
			'phone' 			=> true,
			'beneficiaryid'		=> true,
			'orderid' 			=> true,		/* order id generated by website (me) */
			'amount' 			=> true,		/* amount to transfer */
			'remarks' 			=> true,		/* short description */
		],
	];

	/**
	 * Jolo API required params for verifying agent, beneficiary
	 */
	private $required_params_verify = [
		'agent' => [
			'phone' 			=> true,
			'otp' 				=> true,
		],
		'beneficiary' => [
			'phone' 			=> true,
			'beneficiaryid' 	=> true,
			'otp' 				=> true,		/* otp send to beneficiary mobile number */
		],
		'transfer' => [
			'txn' 				=> true,
		],
	];

	/**
	 * Jolo API required params for getting detail of agent, beneficiary
	 */
	private $required_params_detail = [
		'agent' => [
			'phone' 			=> true,
		],
		'beneficiary' => [
			'beneficiaryid' 	=> true,
		],
		'balance' => [
			// nothing required, just api key
		],
	];

	/**
	 * Jolo API required params for getting detail of agent, beneficiary
	 */
	private $required_params_delete = [
		'beneficiary' => [
			'beneficiaryid' 	=> true,
		],
	];

}